controllers/AddgirlController.php
<?php

namespace app\controllers;

use app\models\Characters;
use app\models\Files;
use app\models\Girls;
use app\models\Languages;
use app\models\Girlslanguages;
use app\models\Logs;
use app\models\Materialstatuses;
use app\models\Occupations;
use app\models\Religions;
use app\models\Staticpages;
use app\models\Statuses;
use app\models\UploadForm;
use app\models\Photoes;
use app\models\Partners;
use app\models\Users;
use app\models\Names;
use app\models\Cities;
use Yii;
use yii\helpers\BaseFileHelper;
use yii\helpers\BaseVarDumper;
use yii\web\Controller;
use yii\web\UploadedFile;

class AddgirlController extends Controller
{
    public function actionIndex()
    {
        $userType = Yii::$app->user->identity->usertypeid;

        if (!empty($userType) && $userType == 2) {
            $userId = Yii::$app->user->identity->id;
            $partnerModel = new Partners();
            $girlsModel = new Girls();


            $partner = $partnerModel->getUser($userId);

            if (!empty($partner)) {
                $partnerGirls = $girlsModel->getGirlsByPartnerId($partner->id);

                return $this->render('index', [
                    'girls' => $partnerGirls,
                    'partner' => $partner
                ]);
            } else {
                return $this->render('index', [
                    'partner' => $partner
                ]);
            }
        } else {
            return $this->goHome();
        }
    }


    /**
     * View girl action
     */
    public function actionView($id)
    {
        $userType = Yii::$app->user->identity->usertypeid;


        if (!empty($userType) && $userType == 2) {
            $girlModel = new Girls();
            $partnerModel = new Partners();
            $characterModel = new Characters();
            $occupationModel = new Occupations();
            $photosModel = new Photoes();
            $filesModel = new Files();
            $girlsLanguageModel = new Girlslanguages();

            $girl = $girlModel->getGirlById($id);
            $userId = Yii::$app->user->identity->id;
            $partner = $partnerModel->getUser($userId);


            if ($girl->partnerid != $partner->id) {
                return $this->goHome();
            }

            $girl->occupationid = $occupationModel->getOccupationById($girl->occupationid);
            $girl->characterid = $characterModel->getCharacterById($girl->characterid);
            $languages = $girlsLanguageModel->getLanguageByGirlId($girl->id);
            $girl->languageid = $languages[0];
            $girl->languageid2 = $languages[1];

            $photo = $photosModel->getPhotoByGirlId($girl->userid);
            if (!empty($photo)) {
                $girl->avatarPath = $filesModel->getFileById($photo->fileid)->path;
            }

            $photos = $photosModel->getAllPhotoByGirlId($girl->userid);
            foreach ($photos as $photo) {
                $photo->filepath = $filesModel->getFileById($photo->fileid)->path;
                $pathMini = explode('/', $filesModel->getFileById($photo->fileid)->path);
                $photo->filepathmini = $pathMini[0] . '/' . $pathMini[1] . '/m_' . $pathMini[2];
            }

            return $this->render('view', [
                'model' => $girl,
                'photos' => $photos
            ]);
        } else {
            return $this->goHome();
        }
    }


    /**
     * Edit girl action
     */
    public function actionEdit($id)
    {
        $userId = Yii::$app->user->identity->id;
        $tmpDir = '../../melia.agency777.com/web/media/tmp/' . $userId;
        $userType = Yii::$app->user->identity->usertypeid;

        if (!empty($userType) && $userType == 2) {
            $girlModel = new Girls();
            $partnerModel = new Partners();
            $girlsLanguagesModel = new Girlslanguages();
            $religionsModel = new Religions();
            $languagesModel = new Languages();
            $characterModel = new Characters();
            $materialStatus = new Materialstatuses();
            $occupationModel = new Occupations();
            $photosModel = new Photoes();
            $filesModel = new Files();
            $namesModel = new Names();
            $citiesModel = new Cities();
            $fileUploadModel = new UploadForm();

            $girl = $girlModel->getGirlById($id);
            $partner = $partnerModel->getUser(Yii::$app->user->id);
            if ($girl->partnerid != $partner->id) {
                return $this->goHome();
            }


            // анкета уже подтверждена и ее нельзя уже изменять
            if ($girl->statusid == 6) {
                return $this->redirect('index');
            } else {
                if (!empty($_POST['Girls'])) {
                    $data = $_POST['Girls'];
                    $girl = $girlModel->getGirlById($data['id']);
                    $data['passportimage'] = $girl->passportimage;
                    $data['identificationvideo'] = $girl->identificationvideo;

                    $girlModel->attributes = $data;
                    $girl->attributes = $data;
                    $girl->setAttributes([
                        'statusid' => 5,
                        'is_active' => 1,
                        'is_aproved' => 0,
                        'is_accepted' => 1,
                        'partnerid' => $partner->id
                    ]);
                    if ($girl->validate()) {
                        $girl->save();

                        $girlsLanguagesModel->addGirlLanguage($girl->id, $data['languageid'], $data['languageid2']);

                        if (file_exists($tmpDir)) {
                            $filesModel->saveTmpFilesToGirl($girl->userid, $tmpDir);
                            BaseFileHelper::removeDirectory($tmpDir);
                        }

                        return $this->redirect(['addgirl/index']);
                    } else {
                        print_r($girl->getErrors());
                    }
                } else {
                    BaseFileHelper::removeDirectory($tmpDir);

                    // show girl profile
                    $religions = $religionsModel->getAllReligions();
                    $languages = $languagesModel->getAllLanguages();
                    $characters = $characterModel->getAllCharacters();
                    $statuses = $materialStatus->getAllStatuses();
                    $occupations = $occupationModel->getAllOccupations();
                    $names = $namesModel->getAllNames();
                    $cities = $citiesModel->getAllCities();

                    $photo = $photosModel->getPhotoByGirlId($girl->userid);
                    if (!empty($photo)) {
                        $girl->avatarPath = $filesModel->getFileById($photo->fileid)->path;
                    }

                    $photos = $photosModel->getAllPhotoByGirlId($girl->userid);
                    foreach ($photos as $photo) {
                        $photo->filepath = $filesModel->getFileById($photo->fileid)->path;
                        $pathMini = explode('/', $filesModel->getFileById($photo->fileid)->path);
                        $photo->filepathmini = $pathMini[0] . '/' . $pathMini[1] . '/m_' . $pathMini[2];
                    }

                    return $this->render('edit', [
                        'model' => $girl,
                        'names' => $names,
                        'cities' => $cities,
                        'photos' => $photos,
                        'fileModel' => $fileUploadModel,
                        'religions' => $religions,
                        'languages' => $languages,
                        'characters' => $characters,
                        'eyescolor' => Yii::$app->params['eyesColor'],
                        'haircolor' => Yii::$app->params['hairColor'],
                        'education' => Yii::$app->params['education'],
                        'statuses' => $statuses,
                        'occupations' => $occupations,
                    ]);
                }
            }
        } else {
            return $this->goHome();
        }
    }

    /**
     * Create new girl action by partner
     */
    public function actionCreate()
    {
        set_time_limit(0);

        $userId = Yii::$app->user->identity->id;

        $logModel = new Logs();
        $isLogs = $logModel->getLogsByUserId($userId);
        $statispagesModel = new Staticpages();

        $tmpDir = '../../melia.agency777.com/web/media/tmp/' . $userId;
        $tmpVideoDir = '../../melia.agency777.com/web/media/tmpVideo/' . $userId;
        $userType = Yii::$app->user->identity->usertypeid;

        if (!empty($userType) && $userType == 2) {
            $partnerModel = new Partners();
            $uploadFormModel = new UploadForm();
            $filesModel = new Files();
            $girlModel = new Girls();
            $girlsLanguagesModel = new Girlslanguages();
            $partner = $partnerModel->getUser(Yii::$app->user->id);

            if (!empty($_POST['Girls']) && !empty($_POST['Users'])) {
                $data = $_POST['Girls'];

                $girlModel->attributes = $data;
                if ($girlModel->validate()) {
                    $userModel = new Users();
                    $newGirlId = $userModel->addGirlUser($data['name'], $data['lastname'], $data['email']);

                    // upload passport image
                    $uploadFormModel->imageFile = UploadedFile::getInstance($uploadFormModel, 'imageFile');
                    $girlModel->passportimage = $uploadFormModel->upload(1, $newGirlId);

                    $girlModel->setAttribute('userid', $newGirlId);
                    $girlModel->setAttributes([
                        'partnerid' => $partner->id,
                        'statusid' => 5,
                        'is_active' => 1,
                        'is_aproved' => 0,
                        'is_accepted' => 1

views/addgirl/index.php
<?php
use yii\helpers\Url;
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use app\components\MenuWidget;

$this->title = 'Girls';
?>
<?php Yii::$app->language = $_COOKIE['lang'];?>
<header>
    <section class="">
        <div class="top-panel">
            <div class="container">
                <div class="brand">
                    <h1 class="brand_name"><a href="<?= Url::toRoute(['index']); ?>"><?= Yii::$app->params['siteName']; ?></a></h1>
                    <p class="brand_slogan">dating site</p>
                </div>
            </div>
        </div>
    </section>
</header>

<!--==============================CONTENT==============================-->
<main>
    <?= MenuWidget::widget(); ?>

    <section class="well center well__06 bg01 shadow filter-block">
        <h2><?=Yii::t('app','Girls')?></h2>
    </section>

    <section class="well center m-height partner-girls">
        <div class="container">
            <?php if(!empty($partner)): ?>
                <?php if($partner->statusid == 6): ?>
                    <a href="<?= Url::toRoute(['addgirl/create']); ?>">
                        <button type="button" class="btn-noshadow"><?= Yii::t('app','Add girl')?></button>
                    </a>
                    <?php if(!empty($girls)): ?>
                        <div class="row">
                            <div class="girls">
                                <?php foreach($girls as $girl): ?>
                                    <a href="<?= Url::toRoute(['view', 'id' => $girl->id]); ?>">
                                        <div class="girl">

                                            <?php $filePath = 'http://meliaagency.com/web/' . $girl->avatarPath; ?>
                                            <?php $file_headers = @get_headers($filePath);?>
                                            <?php if(!empty($girl->avatarPath) && $file_headers[0] == 'HTTP/1.1 200 OK'):?>
                                                <img  src="<?= $filePath; ?>">
                                            <?php else: ?>
                                                <img  src="<?= Yii::$app->getUrlManager()->getBaseUrl() ?>/images/no-image-girl.png" alt="">
                                            <?php endif; ?>
                                            <br>
                                            <span class="name"><?= $girl->name .' '.$girl->lastname; ?></span><br>
                                            <span class="status"><?= Yii::t('app','Status')?>: <?= $girl->status->title; ?></span><br>
                                            <span class="contacts">
                                                <span class="address">
                                                    <i class="fa fa-map-marker"></i><?= $girl->city .', '. $girl->country; ?>
                                                </span><br>
                                                <span class="email"><i class="fa fa-envelope"></i><?= $girl->email; ?></span><br>
                                                <span class="phone"><i class="fa fa-phone"></i><?= $girl->phone; ?></span>
                                            </span>
                                        </div>
                                    </a>
                                <?php endforeach; ?>
                            </div>
                        </div>
                    <?php else: ?>
                        <h5><?= Yii::t('app','You have not registered girls yet')?></h5>
                    <?php endif; ?>
                <?php else: ?>
                    <h5> <?= Yii::t('app',"You can't add girls yet. Your profile doesn't approved") ?></h5>
                <?php endif; ?>
            <?php else: ?>
                <h5><?=Yii::t('app',"Fill your profile to add girls")?></h5>
            <?php endif; ?>
        </div>
    </section>
</main>